services:
  ai-service:
    build: .
    container_name: ipsc-ai-engine
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - ipsc-network

networks:
  ipsc-network:
    driver: bridge
